package view;

import controller.CartController;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Movie;

/**
 *
 * @author Alysson Chinque
 */
public class Cart extends javax.swing.JFrame {

    private final CartController controller;
    private int session;
    private int sizeArray;
    private ArrayList<Movie> moviesArray = new ArrayList<>();
    private javax.swing.JPanel[] panelMovie;
    private javax.swing.JLabel[] imageMovie;
    private javax.swing.JLabel[] titleMovie;
    private javax.swing.JLabel[] subTitleMovie;
    private javax.swing.JLabel[] priceMovie;
    private javax.swing.JButton[] btnDelete;

    /**
     * Creates new form Cart
     */
    public Cart(int session) {
        this.session = session;
        controller = new CartController(this);
        initComponents();
        moviesArray = controller.getMoviesSession(session);
        sizeArray = moviesArray.size();
        genVariables(moviesArray, sizeArray);
        fillVariables(moviesArray, sizeArray);
        positionVariables(sizeArray);
        totalValue(sizeArray);
    }

    public Cart() {
        controller = new CartController(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        subTitleLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        priceTotalLabel = new javax.swing.JLabel();
        checkoutButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(40, 40, 40));
        background.setMaximumSize(new java.awt.Dimension(1200, 800));
        background.setMinimumSize(new java.awt.Dimension(1200, 800));
        background.setPreferredSize(new java.awt.Dimension(1200, 800));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/xtra-vision_400.jpg"))); // NOI18N

        panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel.setPreferredSize(new java.awt.Dimension(1100, 650));

        titleLabel.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        titleLabel.setText("TITLE");
        titleLabel.setMaximumSize(new java.awt.Dimension(80, 30));
        titleLabel.setMinimumSize(new java.awt.Dimension(80, 30));
        titleLabel.setName(""); // NOI18N
        titleLabel.setPreferredSize(new java.awt.Dimension(80, 30));

        subTitleLabel.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        subTitleLabel.setText("SubTitle");
        subTitleLabel.setMaximumSize(new java.awt.Dimension(100, 30));
        subTitleLabel.setMinimumSize(new java.awt.Dimension(100, 30));
        subTitleLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        priceLabel.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        priceLabel.setText("price");
        priceLabel.setMaximumSize(new java.awt.Dimension(510, 20));
        priceLabel.setMinimumSize(new java.awt.Dimension(510, 20));
        priceLabel.setPreferredSize(new java.awt.Dimension(510, 20));

        totalLabel.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        totalLabel.setText("TOTAL");
        totalLabel.setMaximumSize(new java.awt.Dimension(510, 20));
        totalLabel.setMinimumSize(new java.awt.Dimension(510, 20));
        totalLabel.setPreferredSize(new java.awt.Dimension(510, 20));

        priceTotalLabel.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        priceTotalLabel.setText("€€€€€€");
        priceTotalLabel.setMaximumSize(new java.awt.Dimension(510, 20));
        priceTotalLabel.setMinimumSize(new java.awt.Dimension(510, 20));
        priceTotalLabel.setPreferredSize(new java.awt.Dimension(510, 20));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(331, 331, 331)
                .addComponent(subTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178)
                .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(755, 755, 755)
                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(priceTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(subTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(548, 548, 548)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        checkoutButton.setText("CHECKOUT");
        checkoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButtonActionPerformed(evt);
            }
        });

        backButton.setText("BACK TO MOVIES");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(logo))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(logo)
                .addGap(5, 5, 5)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutButtonActionPerformed
        // TODO add your handling code here:
//        if( controller.checkMoviesInTheCart(session)[0] == 0){
//            JOptionPane.showMessageDialog(null, "Cart might be empty");
//        }else{
//            controller.goCheckout(session, sizeArray);
//        }
        controller.goCheckout(session, sizeArray);
    }//GEN-LAST:event_checkoutButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        controller.backMain(session);

    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel background;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceTotalLabel;
    private javax.swing.JLabel subTitleLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables

    private void genVariables(ArrayList<Movie> moviesArray, int sizeArray) {
        try {
            panelMovie = new JPanel[sizeArray];
            imageMovie = new JLabel[sizeArray];
            titleMovie = new JLabel[sizeArray];
            subTitleMovie = new JLabel[sizeArray];
            priceMovie = new JLabel[sizeArray];
            btnDelete = new JButton[sizeArray];

            for (int i = 0; i < sizeArray; i++) {
                panelMovie[i] = new JPanel();
                imageMovie[i] = new JLabel();
                titleMovie[i] = new JLabel();
                titleMovie[i].setFont(new java.awt.Font("Lucida Console", 1, 20));
                subTitleMovie[i] = new JLabel();
                subTitleMovie[i].setFont(new java.awt.Font("Lucida Console", 1, 16));
                priceMovie[i] = new JLabel();
                btnDelete[i] = new JButton();
                btnDelete[i].addActionListener(controller);
                btnDelete[i].setActionCommand(Integer.toString(moviesArray.get(i).getIdMovie()));
            }
        } catch (Exception e) {

        }
    }

    private void fillVariables(ArrayList<Movie> moviesArray, int sizeArray) {
        for (int i = 0; i < sizeArray; i++) {
            try {
                imageMovie[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/moviesToCart/" + moviesArray.get(i).getIdMovie() + ".jpg")));
                titleMovie[i].setText(moviesArray.get(i).getTitle());
                subTitleMovie[i].setText(moviesArray.get(i).getSubTitle());
                priceMovie[i].setText("2.99");
                btnDelete[i].setText("DELETE");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "error : " + e);
                System.out.println("error filling variables: " + e);
            }
        }
    }

    private void positionVariables(int sizeArray) {
        try {
            for (int i = 0; i < sizeArray; i++) {
                imageMovie[i].setBounds(12, 0, 80, 120);
                titleMovie[i].setBounds(105, 45, 410, 30);
                subTitleMovie[i].setBounds(545, 45, 270, 30);
                priceMovie[i].setBounds(825, 45, 80, 30);
                btnDelete[i].setBounds(925, 45, 75, 30);
                panelMovie[i].add(imageMovie[i]);
                panelMovie[i].add(titleMovie[i]);
                panelMovie[i].add(subTitleMovie[i]);
                panelMovie[i].add(priceMovie[i]);
                panelMovie[i].add(btnDelete[i]);
                panel.add(panelMovie[i]);
            }
            int yAxis = 42;
            for (int i = 0; i < sizeArray; i++) {
                panelMovie[i].setBounds(60, yAxis, 1020, 120);
                panelMovie[i].setLayout(null);
                yAxis += 140;
            }
        } catch (Exception e) {
            System.out.println("error positioning variables: " + e);
        }
    }

    public int getSession() {
        return this.session;
    }

    private void totalValue(int sizeArray) {
        switch (sizeArray) {
            case 1:
                priceTotalLabel.setText("2.99");
                break;
            case 2:
                priceTotalLabel.setText("5.98");
                break;
            case 3:
                priceTotalLabel.setText("8.97");
                break;
            case 4:
                priceTotalLabel.setText("11.96");
                break;
        }
    }
}
