/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Rent;

/**
 *
 * @author Alysson Chinque
 */
public class RentConfirmation extends javax.swing.JFrame {

    /**
     * Creates new form RentConfirmation
     */

    public RentConfirmation(Rent rent) {
        
        initComponents();
    }

    private RentConfirmation() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        background = new javax.swing.JPanel();
        returnDateLabel = new javax.swing.JLabel();
        returnDate = new javax.swing.JLabel();
        ballonMessage1 = new javax.swing.JLabel();
        ballonMessage2 = new javax.swing.JLabel();
        ballonMessage3 = new javax.swing.JLabel();
        rentNumberLabel = new javax.swing.JLabel();
        rentNumber = new javax.swing.JLabel();
        dvdImage = new javax.swing.JLabel();
        ballon = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        messageLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setMaximumSize(new java.awt.Dimension(1200, 800));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1200, 800));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1200, 800));

        background.setBackground(new java.awt.Color(40, 40, 40));
        background.setMaximumSize(new java.awt.Dimension(1200, 800));
        background.setMinimumSize(new java.awt.Dimension(1200, 800));
        background.setPreferredSize(new java.awt.Dimension(1200, 800));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnDateLabel.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        returnDateLabel.setForeground(new java.awt.Color(255, 255, 0));
        returnDateLabel.setText("RETURN DATE!");
        background.add(returnDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        returnDate.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        returnDate.setForeground(new java.awt.Color(255, 255, 0));
        returnDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returnDate.setMaximumSize(new java.awt.Dimension(285, 70));
        returnDate.setMinimumSize(new java.awt.Dimension(285, 70));
        returnDate.setPreferredSize(new java.awt.Dimension(285, 70));
        returnDate.setRequestFocusEnabled(false);
        background.add(returnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        ballonMessage1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        ballonMessage1.setText("THIS IS THE NUMBER THAT");
        background.add(ballonMessage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, -1, -1));

        ballonMessage2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        ballonMessage2.setText("COMES PRINTED IN THE DVD CASE.");
        background.add(ballonMessage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, -1, -1));

        ballonMessage3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        ballonMessage3.setText("SAVE IT TO RETURN THE DVD");
        background.add(ballonMessage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 340, -1, -1));

        rentNumberLabel.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        rentNumberLabel.setForeground(new java.awt.Color(255, 0, 0));
        rentNumberLabel.setText("Rent Number");
        background.add(rentNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, -1, -1));

        rentNumber.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        rentNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rentNumber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rentNumber.setMaximumSize(new java.awt.Dimension(130, 70));
        rentNumber.setMinimumSize(new java.awt.Dimension(130, 70));
        rentNumber.setPreferredSize(new java.awt.Dimension(130, 70));
        background.add(rentNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, 130, 70));

        dvdImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/dvd.png"))); // NOI18N
        background.add(dvdImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        ballon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/speechBalloon.png"))); // NOI18N
        background.add(ballon, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/xtra-vision_700.jpg"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 25, -1, -1));

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        background.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 675, 130, 60));

        messageLabel2.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        messageLabel2.setForeground(new java.awt.Color(255, 255, 0));
        messageLabel2.setText("ENJOY THE MOVIE!");
        background.add(messageLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 710, -1, -1));

        jScrollPane1.setViewportView(background);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentConfirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentConfirmation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel ballon;
    private javax.swing.JLabel ballonMessage1;
    private javax.swing.JLabel ballonMessage2;
    private javax.swing.JLabel ballonMessage3;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel dvdImage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel messageLabel2;
    private javax.swing.JLabel rentNumber;
    private javax.swing.JLabel rentNumberLabel;
    private javax.swing.JLabel returnDate;
    private javax.swing.JLabel returnDateLabel;
    // End of variables declaration//GEN-END:variables
}
